services:
#  app:
#    image: openjdk:23-jdk-alpine
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    environment:
#      - DB_HOST=db
#      - DB_PORT=5432
#      - DB_NAME=library
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#    stdin_open: true
#    volumes:
#      - ./logs:/app/logs
#    tty: true
#    depends_on:
#      db:
#        condition: service_healthy

  db:
    container_name: binary-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
